import { StudioShell, formatDate } from "@/components/StudioShell";
import { trpc } from "@/lib/trpc";
import { BadgeDollarSign, BriefcaseBusiness, CircleDollarSign, FileText, Handshake, Loader2, Plus, TrendingUp, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { toast } from "sonner";
import "./commercial.css";

const leadStatusLabel: Record<string, string> = { new: "Novo", qualified: "Qualificado", proposal: "Proposta", negotiation: "Negociação", won: "Ganho", lost: "Perdido", archived: "Arquivado" };
const proposalStatusLabel: Record<string, string> = { draft: "Rascunho", sent: "Enviada", viewed: "Visualizada", accepted: "Aceita", rejected: "Recusada", expired: "Expirada" };
const contractStatusLabel: Record<string, string> = { draft: "Rascunho", active: "Ativo", suspended: "Suspenso", ended: "Encerrado", renewal_due: "Renovação" };
const entryTypeLabel: Record<string, string> = { revenue: "Receita", expense: "Despesa", media_spend: "Mídia paga", refund: "Reembolso" };

export function formatBRL(cents?: number | null) {
  return new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" }).format((cents ?? 0) / 100);
}

function amountToCents(value: string) {
  const amount = Number(value.replace(",", "."));
  return Number.isFinite(amount) ? Math.max(0, Math.round(amount * 100)) : 0;
}

export default function Commercial() {
  const utils = trpc.useUtils();
  const clients = trpc.workspace.clients.useQuery();
  const preferences = trpc.workspace.preferences.useQuery();
  const [clientId, setClientId] = useState<number | null>(null);
  const [leadForm, setLeadForm] = useState({ companyName: "", contactName: "", contactEmail: "", source: "Indicação", monthly: "" });
  const [proposalForm, setProposalForm] = useState({ proposalNumber: "", title: "", scope: "", amount: "", leadId: "" });
  const [contractForm, setContractForm] = useState({ code: "", title: "", scope: "", billingCycle: "monthly" as "monthly" | "annual" | "project", recurring: "", proposalId: "" });
  const [entryForm, setEntryForm] = useState({ entryType: "revenue" as "revenue" | "expense" | "media_spend" | "refund", description: "", amount: "", status: "planned" as "planned" | "invoiced" | "paid" | "overdue" | "cancelled" });

  const leads = trpc.commercial.leads.useQuery();
  const proposals = trpc.commercial.proposals.useQuery(clientId ? { clientId } : undefined);
  const contracts = trpc.commercial.contracts.useQuery(clientId ? { clientId } : undefined);
  const entries = trpc.commercial.financialEntries.useQuery(clientId ? { clientId } : undefined);
  const profitability = trpc.commercial.profitability.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const selectedClient = useMemo(() => clients.data?.find(client => client.id === clientId) ?? null, [clients.data, clientId]);

  useEffect(() => {
    if (clientId !== null || !clients.data?.length) return;
    const preferred = preferences.data?.activeClientId;
    setClientId(preferred && clients.data.some(client => client.id === preferred) ? preferred : clients.data[0].id);
  }, [clientId, clients.data, preferences.data?.activeClientId]);

  const refresh = async () => {
    await Promise.all([utils.commercial.leads.invalidate(), utils.commercial.proposals.invalidate(), utils.commercial.contracts.invalidate(), utils.commercial.financialEntries.invalidate(), utils.commercial.profitability.invalidate()]);
  };
  const createLead = trpc.commercial.createLead.useMutation({ onSuccess: async () => { await refresh(); setLeadForm({ companyName: "", contactName: "", contactEmail: "", source: "Indicação", monthly: "" }); toast.success("Lead registrado no pipeline comercial."); }, onError: error => toast.error(error.message) });
  const updateLead = trpc.commercial.updateLead.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const createProposal = trpc.commercial.createProposal.useMutation({ onSuccess: async () => { await refresh(); setProposalForm({ proposalNumber: "", title: "", scope: "", amount: "", leadId: "" }); toast.success("Proposta registrada para acompanhamento humano."); }, onError: error => toast.error(error.message) });
  const updateProposal = trpc.commercial.updateProposalStatus.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const createContract = trpc.commercial.createContract.useMutation({ onSuccess: async () => { await refresh(); setContractForm({ code: "", title: "", scope: "", billingCycle: "monthly", recurring: "", proposalId: "" }); toast.success("Contrato registrado. Ative-o somente após a formalização externa."); }, onError: error => toast.error(error.message) });
  const updateContract = trpc.commercial.updateContractStatus.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const createEntry = trpc.commercial.createFinancialEntry.useMutation({ onSuccess: async () => { await refresh(); setEntryForm({ entryType: "revenue", description: "", amount: "", status: "planned" }); toast.success("Lançamento financeiro registrado."); }, onError: error => toast.error(error.message) });

  function submitLead(event: FormEvent) { event.preventDefault(); createLead.mutate({ companyName: leadForm.companyName, contactName: leadForm.contactName || null, contactEmail: leadForm.contactEmail || null, source: leadForm.source || null, estimatedMonthlyRevenueCents: leadForm.monthly ? amountToCents(leadForm.monthly) : null }); }
  function submitProposal(event: FormEvent) { event.preventDefault(); if (!clientId) return; createProposal.mutate({ clientId, leadId: proposalForm.leadId ? Number(proposalForm.leadId) : null, proposalNumber: proposalForm.proposalNumber, title: proposalForm.title, scope: proposalForm.scope, amountCents: amountToCents(proposalForm.amount) }); }
  function submitContract(event: FormEvent) { event.preventDefault(); if (!clientId) return; createContract.mutate({ clientId, proposalId: contractForm.proposalId ? Number(contractForm.proposalId) : null, code: contractForm.code, title: contractForm.title, scope: contractForm.scope, billingCycle: contractForm.billingCycle, recurringRevenueCents: contractForm.recurring ? amountToCents(contractForm.recurring) : null }); }
  function submitEntry(event: FormEvent) { event.preventDefault(); if (!clientId) return; createEntry.mutate({ clientId, entryType: entryForm.entryType, status: entryForm.status, description: entryForm.description, amountCents: amountToCents(entryForm.amount) }); }

  return <StudioShell title="Comercial e rentabilidade" eyebrow="Pipeline, contratos e margem"><div className="commercial-page">
    <section className="commercial-hero"><div><p className="commercial-kicker"><TrendingUp size={15} /> do primeiro contato à margem real</p><h2>Uma operação comercial conectada ao valor entregue.</h2><p>Centralize oportunidades, propostas, contratos e lançamentos. Os indicadores são derivados somente dos registros confirmados — sem estimativas ocultas ou métricas inventadas.</p></div><label className="commercial-picker">Cliente em análise<select value={clientId ?? ""} onChange={event => setClientId(Number(event.target.value))} disabled={!clients.data?.length}><option value="" disabled>Selecione um cliente</option>{(clients.data ?? []).map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label></section>

    <section className="commercial-metrics" aria-label="Indicadores de rentabilidade">
      <article><span><CircleDollarSign size={17} /></span><small>Receita líquida registrada</small><strong>{profitability.data ? formatBRL(profitability.data.revenueCents - profitability.data.refundCents) : "—"}</strong><p>Receitas menos reembolsos em lançamentos faturados, pagos ou vencidos.</p></article>
      <article><span><BadgeDollarSign size={17} /></span><small>Margem apurada</small><strong>{profitability.data ? formatBRL(profitability.data.marginCents) : "—"}</strong><p>{profitability.data?.marginPercent == null ? "Depende de receitas registradas." : `${profitability.data.marginPercent}% sobre a receita líquida.`}</p></article>
      <article><span><Handshake size={17} /></span><small>MRR contratado</small><strong>{profitability.data ? formatBRL(profitability.data.mrrCents) : "—"}</strong><p>Somente contratos ativos com recorrência cadastrada.</p></article>
      <article><span><BriefcaseBusiness size={17} /></span><small>Horas registradas</small><strong>{profitability.data ? `${profitability.data.hoursWorked} h` : "—"}</strong><p>{profitability.data?.overdueEntries ?? 0} lançamento(s) financeiro(s) vencido(s).</p></article>
    </section>

    <section className="commercial-grid">
      <article className="commercial-panel commercial-leads"><header><div><p className="commercial-kicker"><UsersRound size={14} /> pipeline CRM</p><h3>Oportunidades</h3><p>Qualifique o próximo passo e mantenha a decisão comercial rastreável.</p></div><span>{leads.data?.length ?? 0} lead(s)</span></header><form onSubmit={submitLead} className="commercial-form compact"><input required value={leadForm.companyName} onChange={event => setLeadForm(current => ({ ...current, companyName: event.target.value }))} placeholder="Empresa do lead" /><input value={leadForm.contactName} onChange={event => setLeadForm(current => ({ ...current, contactName: event.target.value }))} placeholder="Contato" /><input type="email" value={leadForm.contactEmail} onChange={event => setLeadForm(current => ({ ...current, contactEmail: event.target.value }))} placeholder="E-mail" /><input value={leadForm.monthly} inputMode="decimal" onChange={event => setLeadForm(current => ({ ...current, monthly: event.target.value }))} placeholder="MRR estimado (R$)" /><button className="ops-primary-button" disabled={createLead.isPending} type="submit">{createLead.isPending ? <Loader2 size={15} /> : <Plus size={15} />} Novo lead</button></form><div className="commercial-list">{!leads.data?.length ? <p className="commercial-empty">Ainda não há leads. Registre apenas oportunidades reais.</p> : leads.data.map(({ lead, responsible, convertedClient }) => <div className="commercial-row" key={lead.id}><div><strong>{lead.companyName}</strong><small>{lead.contactName || lead.contactEmail || "Contato a definir"} {responsible?.name ? `· ${responsible.name}` : ""}</small><small>{lead.nextActionAt ? `Próximo passo: ${formatDate(lead.nextActionAt)}` : "Próximo passo ainda não definido"}{convertedClient?.name ? ` · Cliente: ${convertedClient.name}` : ""}</small></div><select value={lead.status} onChange={event => updateLead.mutate({ leadId: lead.id, status: event.target.value as "new" | "qualified" | "proposal" | "negotiation" | "won" | "lost" | "archived" })}>{Object.entries(leadStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>)}</div></article>

      <article className="commercial-panel"><header><div><p className="commercial-kicker"><FileText size={14} /> proposta estruturada</p><h3>Propostas</h3><p>Escopo, valor e decisão comercial em um único registro.</p></div><span>{proposals.data?.length ?? 0} proposta(s)</span></header><form onSubmit={submitProposal} className="commercial-form"><input required value={proposalForm.proposalNumber} onChange={event => setProposalForm(current => ({ ...current, proposalNumber: event.target.value }))} placeholder="Número da proposta" /><input required value={proposalForm.title} onChange={event => setProposalForm(current => ({ ...current, title: event.target.value }))} placeholder="Título" /><input required value={proposalForm.amount} inputMode="decimal" onChange={event => setProposalForm(current => ({ ...current, amount: event.target.value }))} placeholder="Valor (R$)" /><select value={proposalForm.leadId} onChange={event => setProposalForm(current => ({ ...current, leadId: event.target.value }))}><option value="">Sem vínculo com lead</option>{(leads.data ?? []).map(({ lead }) => <option value={lead.id} key={lead.id}>{lead.companyName}</option>)}</select><textarea required value={proposalForm.scope} onChange={event => setProposalForm(current => ({ ...current, scope: event.target.value }))} placeholder="Escopo aprovado para a proposta" /><button className="ops-primary-button" disabled={!clientId || createProposal.isPending} type="submit">{createProposal.isPending ? <Loader2 size={15} /> : <Plus size={15} />} Registrar proposta</button></form><div className="commercial-list">{!proposals.data?.length ? <p className="commercial-empty">Nenhuma proposta vinculada a {selectedClient?.name ?? "este cliente"}.</p> : proposals.data.map(({ proposal, lead, client }) => <div className="commercial-row" key={proposal.id}><div><strong>{proposal.proposalNumber} · {proposal.title}</strong><small>{formatBRL(proposal.amountCents)} · {lead?.companyName ?? client?.name ?? "Sem referência"}</small></div><select value={proposal.status} onChange={event => updateProposal.mutate({ proposalId: proposal.id, status: event.target.value as "draft" | "sent" | "viewed" | "accepted" | "rejected" | "expired" })}>{Object.entries(proposalStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>)}</div></article>

      <article className="commercial-panel"><header><div><p className="commercial-kicker"><Handshake size={14} /> receita contratada</p><h3>Contratos</h3><p>Ative somente depois da formalização e da conferência humana do acordo.</p></div><span>{contracts.data?.length ?? 0} contrato(s)</span></header><form onSubmit={submitContract} className="commercial-form"><input required value={contractForm.code} onChange={event => setContractForm(current => ({ ...current, code: event.target.value }))} placeholder="Código" /><input required value={contractForm.title} onChange={event => setContractForm(current => ({ ...current, title: event.target.value }))} placeholder="Nome do contrato" /><select value={contractForm.billingCycle} onChange={event => setContractForm(current => ({ ...current, billingCycle: event.target.value as "monthly" | "annual" | "project" }))}><option value="monthly">Mensal</option><option value="annual">Anual</option><option value="project">Projeto</option></select><input value={contractForm.recurring} inputMode="decimal" onChange={event => setContractForm(current => ({ ...current, recurring: event.target.value }))} placeholder="Receita recorrente (R$)" /><select value={contractForm.proposalId} onChange={event => setContractForm(current => ({ ...current, proposalId: event.target.value }))}><option value="">Sem proposta vinculada</option>{(proposals.data ?? []).map(({ proposal }) => <option value={proposal.id} key={proposal.id}>{proposal.proposalNumber}</option>)}</select><textarea required value={contractForm.scope} onChange={event => setContractForm(current => ({ ...current, scope: event.target.value }))} placeholder="Escopo contratado" /><button className="ops-primary-button" disabled={!clientId || createContract.isPending} type="submit">{createContract.isPending ? <Loader2 size={15} /> : <Plus size={15} />} Registrar contrato</button></form><div className="commercial-list">{!contracts.data?.length ? <p className="commercial-empty">Nenhum contrato para este cliente.</p> : contracts.data.map(({ contract }) => <div className="commercial-row" key={contract.id}><div><strong>{contract.code} · {contract.title}</strong><small>{contract.billingCycle === "monthly" ? `MRR: ${formatBRL(contract.recurringRevenueCents)}` : contract.billingCycle === "annual" ? `Anual: ${formatBRL(contract.recurringRevenueCents)}` : "Projeto pontual"}</small></div><select value={contract.status} onChange={event => clientId && updateContract.mutate({ clientId, contractId: contract.id, status: event.target.value as "draft" | "active" | "suspended" | "ended" | "renewal_due" })}>{Object.entries(contractStatusLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>)}</div></article>

      <article className="commercial-panel"><header><div><p className="commercial-kicker"><CircleDollarSign size={14} /> visão financeira</p><h3>Lançamentos</h3><p>Registre apenas valores confirmados ou explicitamente planejados para leitura honesta da margem.</p></div><span>{entries.data?.length ?? 0} lançamento(s)</span></header><form onSubmit={submitEntry} className="commercial-form compact"><select value={entryForm.entryType} onChange={event => setEntryForm(current => ({ ...current, entryType: event.target.value as typeof current.entryType }))}>{Object.entries(entryTypeLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select><select value={entryForm.status} onChange={event => setEntryForm(current => ({ ...current, status: event.target.value as typeof current.status }))}><option value="planned">Planejado</option><option value="invoiced">Faturado</option><option value="paid">Pago</option><option value="overdue">Vencido</option><option value="cancelled">Cancelado</option></select><input required value={entryForm.description} onChange={event => setEntryForm(current => ({ ...current, description: event.target.value }))} placeholder="Descrição" /><input required value={entryForm.amount} inputMode="decimal" onChange={event => setEntryForm(current => ({ ...current, amount: event.target.value }))} placeholder="Valor (R$)" /><button className="ops-primary-button" disabled={!clientId || createEntry.isPending} type="submit">{createEntry.isPending ? <Loader2 size={15} /> : <Plus size={15} />} Adicionar lançamento</button></form><div className="commercial-list">{!entries.data?.length ? <p className="commercial-empty">Nenhum lançamento financeiro para este cliente.</p> : entries.data.map(({ entry }) => <div className="commercial-row" key={entry.id}><div><strong>{entryTypeLabel[entry.entryType]} · {entry.description}</strong><small>{formatBRL(entry.amountCents)} · {entry.status === "planned" ? "Planejado" : entry.status === "invoiced" ? "Faturado" : entry.status === "paid" ? "Pago" : entry.status === "overdue" ? "Vencido" : "Cancelado"}</small></div><span className={`commercial-entry-type ${entry.entryType}`}>{entry.entryType === "revenue" ? "+" : "−"}</span></div>)}</div></article>
    </section>
  </div></StudioShell>;
}
