import { StudioShell, formatDate } from "@/components/StudioShell";
import { trpc } from "@/lib/trpc";
import { CalendarPlus, CircleDotDashed, Link2, Loader2, Plus, Search, Target, TrendingUp } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import "./intelligence.css";

const cents = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const editorialLabels: Record<string, string> = { idea: "Ideia", briefing: "Briefing", production: "Produção", review: "Revisão", approved: "Aprovado", published: "Publicado", archived: "Arquivado" };
const researchLabels: Record<string, string> = { draft: "Rascunho", collecting: "Coleta", review: "Em revisão", accepted: "Validado", archived: "Arquivado" };

function toCents(value: FormDataEntryValue | null) {
  return Math.max(0, Math.round(Number(String(value ?? "0").replace(",", ".")) * 100));
}

export default function Intelligence() {
  const utils = trpc.useUtils();
  const preferences = trpc.workspace.preferences.useQuery();
  const clients = trpc.workspace.clients.useQuery();
  const [composer, setComposer] = useState<"editorial" | "media" | "snapshot" | "research" | "source" | null>(null);
  const [selectedResearchId, setSelectedResearchId] = useState<number | null>(null);
  const clientId = preferences.data?.activeClientId ?? clients.data?.[0]?.id ?? 0;
  const clientInput = useMemo(() => ({ clientId }), [clientId]);
  const editorial = trpc.intelligence.editorialItems.useQuery(clientInput, { enabled: clientId > 0 });
  const editorialItems = (editorial.data ?? []).map(row => row.item);
  const mediaPlans = trpc.intelligence.mediaPlans.useQuery(clientInput, { enabled: clientId > 0 });
  const mediaSummary = trpc.intelligence.mediaSummary.useQuery(clientInput, { enabled: clientId > 0 });
  const researches = trpc.intelligence.researches.useQuery(clientInput, { enabled: clientId > 0 });
  const sourceInput = useMemo(() => ({ clientId, researchId: selectedResearchId ?? 0 }), [clientId, selectedResearchId]);
  const sources = trpc.intelligence.researchSources.useQuery(sourceInput, { enabled: clientId > 0 && selectedResearchId !== null });
  const invalidate = async () => Promise.all([utils.intelligence.editorialItems.invalidate(), utils.intelligence.mediaPlans.invalidate(), utils.intelligence.mediaSummary.invalidate(), utils.intelligence.researches.invalidate(), utils.intelligence.researchSources.invalidate()]);
  const createEditorial = trpc.intelligence.createEditorialItem.useMutation({ onSuccess: async () => { await invalidate(); setComposer(null); toast.success("Pauta registrada no calendário editorial."); }, onError: error => toast.error(error.message) });
  const updateEditorial = trpc.intelligence.updateEditorialItem.useMutation({ onSuccess: async () => { await invalidate(); toast.success("Status editorial atualizado."); }, onError: error => toast.error(error.message) });
  const createMediaPlan = trpc.intelligence.createMediaPlan.useMutation({ onSuccess: async () => { await invalidate(); setComposer(null); toast.success("Plano de mídia criado."); }, onError: error => toast.error(error.message) });
  const createSnapshot = trpc.intelligence.createMediaSnapshot.useMutation({ onSuccess: async () => { await invalidate(); setComposer(null); toast.success("Dados de mídia adicionados."); }, onError: error => toast.error(error.message) });
  const createResearch = trpc.intelligence.createResearch.useMutation({ onSuccess: async ({ id }) => { await invalidate(); setSelectedResearchId(id); setComposer(null); toast.success("Dossiê de pesquisa aberto."); }, onError: error => toast.error(error.message) });
  const updateResearch = trpc.intelligence.updateResearch.useMutation({ onSuccess: async () => { await invalidate(); toast.success("Estado da pesquisa atualizado."); }, onError: error => toast.error(error.message) });
  const addSource = trpc.intelligence.addResearchSource.useMutation({ onSuccess: async () => { await invalidate(); setComposer(null); toast.success("Fonte vinculada ao dossiê."); }, onError: error => toast.error(error.message) });

  function submitEditorial(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const planned = String(data.get("plannedFor") ?? ""); createEditorial.mutate({ clientId, title: String(data.get("title") ?? ""), channel: String(data.get("channel")) as "instagram" | "facebook" | "tiktok" | "youtube" | "linkedin" | "blog" | "email" | "whatsapp" | "other", format: String(data.get("format") ?? "") || null, pillar: String(data.get("pillar") ?? "") || null, objective: String(data.get("objective") ?? "") || null, brief: String(data.get("brief") ?? "") || null, plannedFor: planned ? new Date(`${planned}T12:00:00`) : null }); }
  function submitMedia(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const starts = String(data.get("startsAt") ?? ""); const ends = String(data.get("endsAt") ?? ""); createMediaPlan.mutate({ clientId, name: String(data.get("name") ?? ""), platform: String(data.get("platform")) as "meta" | "google" | "tiktok" | "linkedin" | "other", objective: String(data.get("objective") ?? ""), targetMetric: String(data.get("targetMetric") ?? "") || null, plannedBudgetCents: toCents(data.get("budget")), startsAt: starts ? new Date(`${starts}T12:00:00`) : null, endsAt: ends ? new Date(`${ends}T12:00:00`) : null }); }
  function submitSnapshot(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); createSnapshot.mutate({ clientId, mediaPlanId: Number(data.get("mediaPlanId")), recordedAt: new Date(`${String(data.get("recordedAt"))}T12:00:00`), spendCents: toCents(data.get("spend")), impressions: Number(data.get("impressions") || 0), reach: Number(data.get("reach") || 0), clicks: Number(data.get("clicks") || 0), leads: Number(data.get("leads") || 0), conversions: Number(data.get("conversions") || 0), conversionValueCents: toCents(data.get("conversionValue")), notes: String(data.get("notes") ?? "") || null }); }
  function submitResearch(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); createResearch.mutate({ clientId, title: String(data.get("title") ?? ""), objective: String(data.get("objective") ?? ""), question: String(data.get("question") ?? ""), audience: String(data.get("audience") ?? "") || null, market: String(data.get("market") ?? "") || null }); }
  function submitSource(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!selectedResearchId) return; const data = new FormData(event.currentTarget); addSource.mutate({ clientId, researchId: selectedResearchId, sourceType: String(data.get("sourceType")) as "web" | "social" | "video" | "community" | "report" | "competitor" | "other", title: String(data.get("title") ?? ""), url: String(data.get("url") ?? ""), publisher: String(data.get("publisher") ?? "") || null, excerpt: String(data.get("excerpt") ?? "") || null }); }

  if (!clients.isLoading && !clientId) return <StudioShell title="Planejamento & inteligência" eyebrow="02 · Estratégia, pesquisa e mídia"><div className="ops-content"><section className="ops-empty"><p>Cadastre ou selecione um cliente no filtro superior para iniciar o planejamento de marketing.</p></section></div></StudioShell>;

  return <StudioShell title="Planejamento & inteligência" eyebrow="02 · Estratégia, pesquisa e mídia" actions={<button type="button" className="ops-primary-button" onClick={() => setComposer("research")}><Search size={17} /> Nova pesquisa</button>}>
    <div className="ops-content intelligence-page">
      <section className="ops-page-intro"><div><p className="ops-section-kicker">Cliente ativo</p><h2>Planeje, acompanhe sinais e transforme evidências em decisões revisáveis.</h2><p className="intelligence-intro-copy">Dados de mídia são registrados ou importados sob revisão. Pesquisas não executam coleta automática: as fontes são adicionadas e validadas pela equipe.</p></div><div className="ops-button-group"><button type="button" className="ops-outline-button" onClick={() => setComposer("editorial")}><CalendarPlus size={17} /> Nova pauta</button><button type="button" className="ops-outline-button" onClick={() => setComposer("media")}><TrendingUp size={17} /> Plano de mídia</button></div></section>
      <section className="intelligence-metrics" aria-label="Resumo de conteúdo, mídia e pesquisa"><Metric icon={<CalendarPlus size={18} />} label="Pautas em curso" value={String(editorialItems.filter(item => !["published", "archived"].includes(item.status)).length)} detail={`${editorialItems.filter(item => item.status === "review").length} em revisão`} /><Metric icon={<TrendingUp size={18} />} label="Mídia registrada" value={cents.format((mediaSummary.data?.spendCents ?? 0) / 100)} detail={`${mediaSummary.data?.plans.active ?? 0} plano(s) ativo(s)`} /><Metric icon={<Search size={18} />} label="Dossiês ativos" value={String((researches.data ?? []).filter(row => !["accepted", "archived"].includes(row.status)).length)} detail={`${(researches.data ?? []).filter(row => row.status === "review").length} aguardando validação`} /></section>
      <section className="intelligence-grid">
        <article className="ops-panel intelligence-panel"><PanelHeading kicker="Calendário editorial" title="Pautas e entregas" icon={<CalendarPlus size={20} />} action={<button type="button" className="ops-text-button" onClick={() => setComposer("editorial")}>Adicionar</button>} /><div className="intelligence-list">{editorial.isLoading ? <Loading /> : !editorialItems.length ? <Empty copy="Ainda não há pautas. Crie a primeira ideia com canal, formato e objetivo." /> : editorialItems.slice(0, 8).map(item => <div className="intelligence-row" key={item.id}><span className={`intelligence-status ${item.status}`}>{editorialLabels[item.status]}</span><div><strong>{item.title}</strong><small>{item.channel} · {item.pillar || "Sem pilar"} · {formatDate(item.plannedFor)}</small></div><select aria-label={`Atualizar status de ${item.title}`} value={item.status} onChange={event => updateEditorial.mutate({ clientId, itemId: item.id, status: event.target.value as "idea" | "briefing" | "production" | "review" | "approved" | "published" | "archived", ...(event.target.value === "published" ? { publishedAt: new Date() } : {}) })}>{Object.entries(editorialLabels).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></div>)}</div></article>
        <article className="ops-panel intelligence-panel"><PanelHeading kicker="Mídia paga" title="Metas e resultado" icon={<TrendingUp size={20} />} action={<button type="button" className="ops-text-button" onClick={() => setComposer("snapshot")} disabled={!(mediaPlans.data?.length)}>Registrar dados</button>} /><div className="intelligence-media-summary"><span><b>{mediaSummary.data?.ctrPercent ?? "—"}{mediaSummary.data?.ctrPercent !== null ? "%" : ""}</b><small>CTR</small></span><span><b>{mediaSummary.data?.roas ?? "—"}</b><small>ROAS</small></span><span><b>{mediaSummary.data?.leads ?? 0}</b><small>Leads</small></span></div><div className="intelligence-list">{mediaPlans.isLoading ? <Loading /> : !(mediaPlans.data?.length) ? <Empty copy="Crie um plano antes de registrar resultados ou comparar metas." /> : mediaPlans.data.slice(0, 6).map(plan => <div className="intelligence-row media" key={plan.id}><span className={`intelligence-platform ${plan.platform}`}>{plan.platform}</span><div><strong>{plan.name}</strong><small>{plan.objective} · orçamento {cents.format(plan.plannedBudgetCents / 100)}</small></div><span className={`intelligence-status ${plan.status}`}>{plan.status === "active" ? "Ativo" : plan.status === "paused" ? "Pausado" : plan.status === "completed" ? "Encerrado" : "Rascunho"}</span></div>)}</div></article>
        <article className="ops-panel intelligence-panel intelligence-research"><PanelHeading kicker="Pesquisa sob demanda" title="Dossiês e fontes" icon={<Search size={20} />} action={<button type="button" className="ops-text-button" onClick={() => setComposer("research")}>Abrir dossiê</button>} /><div className="intelligence-research-layout"><div className="intelligence-list">{researches.isLoading ? <Loading /> : !(researches.data?.length) ? <Empty copy="Formule uma pergunta de marketing e registre as fontes verificadas no dossiê." /> : researches.data?.map(research => <button type="button" onClick={() => setSelectedResearchId(research.id)} className={selectedResearchId === research.id ? "intelligence-research-item is-selected" : "intelligence-research-item"} key={research.id}><span className={`intelligence-status ${research.status}`}>{researchLabels[research.status]}</span><strong>{research.title}</strong><small>{research.objective}</small></button>)}</div><div className="intelligence-sources">{selectedResearchId === null ? <Empty copy="Selecione um dossiê para revisar fontes e registrar evidências." /> : <><div className="intelligence-source-heading"><div><p>Fontes verificáveis</p><strong>{sources.data?.length ?? 0} vinculada(s)</strong></div><button type="button" className="ops-icon-button" title="Adicionar fonte" onClick={() => setComposer("source")}><Link2 size={16} /></button></div>{sources.isLoading ? <Loading /> : (sources.data ?? []).map(source => <a key={source.id} className="intelligence-source" href={source.url} target="_blank" rel="noreferrer"><span>{source.sourceType}</span><strong>{source.title}</strong><small>{source.publisher || new URL(source.url).hostname}</small></a>)}{sources.data?.length ? null : <Empty copy="Ainda não há fontes. Adicione apenas referências que possam ser verificadas." />}</>}</div></div></article>
      </section>
      <section className="intelligence-note"><CircleDotDashed size={18} /><p><strong>Uso do Agent-Reach.</strong> A VERTEX registra a pergunta, o objetivo e as fontes de cada pesquisa. O Agent-Reach orienta a investigação profunda sob demanda; a síntese, a recomendação e qualquer publicação permanecem sujeitas à revisão humana.</p></section>
    </div>
    {composer === "editorial" ? <Composer title="Nova pauta editorial" onClose={() => setComposer(null)} pending={createEditorial.isPending} onSubmit={submitEditorial}><label>Título<input name="title" required minLength={2} placeholder="Ex.: Carrossel sobre tendências do setor" /></label><label>Canal<select name="channel" defaultValue="instagram"><option value="instagram">Instagram</option><option value="linkedin">LinkedIn</option><option value="tiktok">TikTok</option><option value="youtube">YouTube</option><option value="blog">Blog</option><option value="email">E-mail</option><option value="whatsapp">WhatsApp</option><option value="other">Outro</option></select></label><label>Formato<input name="format" placeholder="Ex.: Carrossel" /></label><label>Pilar<input name="pillar" placeholder="Ex.: Educação" /></label><label>Data planejada<input name="plannedFor" type="date" /></label><label className="full">Objetivo<input name="objective" placeholder="Ex.: Gerar demanda qualificada" /></label><label className="full">Briefing<textarea name="brief" rows={4} placeholder="Contexto, mensagem, CTA, direcionamento de marca e validações necessárias." /></label></Composer> : null}
    {composer === "media" ? <Composer title="Novo plano de mídia" onClose={() => setComposer(null)} pending={createMediaPlan.isPending} onSubmit={submitMedia}><label>Nome<input name="name" required minLength={2} placeholder="Ex.: Captação Setembro" /></label><label>Plataforma<select name="platform" defaultValue="meta"><option value="meta">Meta</option><option value="google">Google</option><option value="tiktok">TikTok</option><option value="linkedin">LinkedIn</option><option value="other">Outra</option></select></label><label>Objetivo<input name="objective" required placeholder="Ex.: Leads" /></label><label>Métrica-alvo<input name="targetMetric" placeholder="Ex.: CPL" /></label><label>Orçamento (R$)<input name="budget" type="number" min="0" step="0.01" required /></label><label>Início<input name="startsAt" type="date" /></label><label>Encerramento<input name="endsAt" type="date" /></label></Composer> : null}
    {composer === "snapshot" ? <Composer title="Registrar dados de mídia" onClose={() => setComposer(null)} pending={createSnapshot.isPending} onSubmit={submitSnapshot}><label className="full">Plano<select name="mediaPlanId" required>{(mediaPlans.data ?? []).map(plan => <option key={plan.id} value={plan.id}>{plan.name} · {plan.platform}</option>)}</select></label><label>Data<input name="recordedAt" type="date" required /></label><label>Investimento (R$)<input name="spend" type="number" min="0" step="0.01" required /></label><label>Impressões<input name="impressions" type="number" min="0" defaultValue="0" /></label><label>Alcance<input name="reach" type="number" min="0" defaultValue="0" /></label><label>Cliques<input name="clicks" type="number" min="0" defaultValue="0" /></label><label>Leads<input name="leads" type="number" min="0" defaultValue="0" /></label><label>Conversões<input name="conversions" type="number" min="0" defaultValue="0" /></label><label>Valor de conversão (R$)<input name="conversionValue" type="number" min="0" step="0.01" defaultValue="0" /></label><label className="full">Notas<textarea name="notes" rows={3} placeholder="Contexto, mudança de orçamento ou hipótese de otimização." /></label></Composer> : null}
    {composer === "research" ? <Composer title="Abrir dossiê de pesquisa" onClose={() => setComposer(null)} pending={createResearch.isPending} onSubmit={submitResearch}><label>Título<input name="title" required minLength={2} placeholder="Ex.: Mapeamento de objeções no segmento" /></label><label>Objetivo<input name="objective" required placeholder="Ex.: Refinar proposta de valor" /></label><label>Mercado<input name="market" placeholder="Ex.: Materiais de acabamento" /></label><label>Público<input name="audience" placeholder="Ex.: Arquitetos e consumidores" /></label><label className="full">Pergunta de pesquisa<textarea name="question" rows={5} required minLength={3} placeholder="Que necessidade, tendência, concorrente ou comportamento a investigação deve esclarecer?" /></label></Composer> : null}
    {composer === "source" ? <Composer title="Adicionar fonte verificada" onClose={() => setComposer(null)} pending={addSource.isPending} onSubmit={submitSource}><label>Título<input name="title" required minLength={2} placeholder="Título da matéria, relatório ou publicação" /></label><label>Tipo<select name="sourceType" defaultValue="web"><option value="web">Web</option><option value="report">Relatório</option><option value="social">Rede social</option><option value="video">Vídeo</option><option value="community">Comunidade</option><option value="competitor">Concorrente</option><option value="other">Outro</option></select></label><label className="full">URL<input name="url" type="url" required placeholder="https://…" /></label><label className="full">Publicador<input name="publisher" placeholder="Organização ou autor" /></label><label className="full">Trecho ou evidência<textarea name="excerpt" rows={4} placeholder="Registre o dado relevante e a interpretação que será revisada pela equipe." /></label></Composer> : null}
  </StudioShell>;
}

function Metric({ icon, label, value, detail }: { icon: React.ReactNode; label: string; value: string; detail: string }) { return <article><span>{icon}</span><div><p>{label}</p><strong>{value}</strong><small>{detail}</small></div></article>; }
function PanelHeading({ kicker, title, icon, action }: { kicker: string; title: string; icon: React.ReactNode; action?: React.ReactNode }) { return <div className="ops-panel-heading"><div><p className="ops-section-kicker">{kicker}</p><h2>{title}</h2></div><div className="intelligence-panel-action">{icon}{action}</div></div>; }
function Loading() { return <div className="ops-inline-loading"><Loader2 size={16} className="spin" /> Atualizando dados…</div>; }
function Empty({ copy }: { copy: string }) { return <div className="ops-empty"><p>{copy}</p></div>; }
function Composer({ title, children, onClose, onSubmit, pending }: { title: string; children: React.ReactNode; onClose: () => void; onSubmit: (event: FormEvent<HTMLFormElement>) => void; pending: boolean }) { return <div className="ops-modal-backdrop" role="presentation"><section className="ops-modal intelligence-composer" role="dialog" aria-modal="true" aria-label={title}><div className="ops-modal-heading"><div><p className="ops-section-kicker">Inteligência VERTEX</p><h2>{title}</h2></div><button type="button" className="ops-icon-button" onClick={onClose} aria-label="Fechar">×</button></div><form className="ops-form-grid" onSubmit={onSubmit}>{children}<div className="ops-form-actions full"><button className="ops-ghost-button" type="button" onClick={onClose}>Cancelar</button><button className="ops-primary-button" type="submit" disabled={pending}>{pending ? <Loader2 size={16} className="spin" /> : <Plus size={16} />} Salvar</button></div></form></section></div>; }
