import { StudioShell, formatDate } from "@/components/StudioShell";
import { trpc } from "@/lib/trpc";
import { BellRing, Check, ClipboardCheck, ExternalLink, FileDown, FileText, Gauge, KeyRound, Link2, Loader2, Palette, ShieldCheck, TicketCheck, UserPlus, UsersRound } from "lucide-react";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { Link } from "wouter";
import { toast } from "sonner";
import "./whatsapp-saas.css";
import "./success.css";

type GrantRole = "client_admin" | "manager" | "reviewer" | "viewer";
type OnboardingStep = "brand" | "contacts" | "ai" | "whatsapp" | "goals" | "review" | "complete";

const onboardingSteps: Array<{ key: Exclude<OnboardingStep, "complete">; label: string; description: string }> = [
  { key: "brand", label: "Marca", description: "Diretrizes e referências aprovadas." },
  { key: "contacts", label: "Contatos", description: "Responsáveis e acessos confirmados." },
  { key: "ai", label: "IA", description: "Provedor validado ou plano VERTEX definido." },
  { key: "whatsapp", label: "Atendimento", description: "Canal e política de handoff configurados." },
  { key: "goals", label: "Objetivos", description: "Metas e escopo comercial registrados." },
  { key: "review", label: "Revisão", description: "Conferência humana antes da operação." },
];

const notificationLabels = { approvals: "Aprovações externas", usage_limit: "Limites de uso de IA", channel_status: "Status de canais", email_failures: "Falhas de e-mail", due_dates: "Prazos e vencimentos", billing: "Cobrança e assinatura", support: "Tickets de suporte" } as const;
type NotificationEvent = keyof typeof notificationLabels;

export function splitGuidelineList(value: string) { return value.split(/[\n,]/).map(item => item.trim()).filter(Boolean); }

export default function Success() {
  const utils = trpc.useUtils();
  const clients = trpc.workspace.clients.useQuery();
  const preferences = trpc.workspace.preferences.useQuery();
  const [clientId, setClientId] = useState<number | null>(null);
  const [grant, setGrant] = useState({ email: "", displayName: "", role: "viewer" as GrantRole });
  const [completedSteps, setCompletedSteps] = useState<OnboardingStep[]>([]);
  const [onboardingForm, setOnboardingForm] = useState({ currentStep: "brand" as OnboardingStep, goals: "", reviewNote: "" });
  const [brand, setBrand] = useState({ colors: "", fonts: "", toneOfVoice: "", prohibitedWords: "", approvedCtas: "", products: "", differentiators: "" });
  const [notificationEvents, setNotificationEvents] = useState<Record<NotificationEvent, boolean>>({ approvals: true, usage_limit: true, channel_status: true, email_failures: true, due_dates: true, billing: true, support: true });
  const [reportForm, setReportForm] = useState({ title: "Relatório executivo VERTEX", summary: "", periodStart: new Date(new Date().getFullYear(), new Date().getMonth(), 1).toISOString().slice(0, 10), periodEnd: new Date().toISOString().slice(0, 10) });
  const [approvalForm, setApprovalForm] = useState({ campaignId: "", creativeVersionId: "", recipientEmail: "", expiresAt: new Date(Date.now() + 7 * 86_400_000).toISOString().slice(0, 16) });
  const [createdApprovalUrl, setCreatedApprovalUrl] = useState<string | null>(null);

  const health = trpc.success.health.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const grants = trpc.success.accessGrants.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const onboarding = trpc.success.onboarding.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const guidelines = trpc.success.brandGuidelines.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const notifications = trpc.success.notificationPreferences.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const reports = trpc.success.executiveReports.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const approvals = trpc.success.externalApprovalLinks.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const agency = trpc.agency.overview.useQuery({ clientId: clientId ?? 0 }, { enabled: clientId !== null });
  const selectedCampaignId = Number(approvalForm.campaignId) || 0;
  const creativeVersions = trpc.agency.versions.useQuery({ campaignId: selectedCampaignId }, { enabled: selectedCampaignId > 0 });
  const backup = trpc.success.exportClientBackup.useQuery({ clientId: clientId ?? 0 }, { enabled: false, retry: false });
  const selectedClient = useMemo(() => clients.data?.find(item => item.id === clientId) ?? null, [clients.data, clientId]);

  useEffect(() => {
    if (clientId !== null || !clients.data?.length) return;
    const preferred = preferences.data?.activeClientId;
    setClientId(preferred && clients.data.some(item => item.id === preferred) ? preferred : clients.data[0].id);
  }, [clientId, clients.data, preferences.data?.activeClientId]);
  useEffect(() => { if (onboarding.data) { setCompletedSteps(onboarding.data.completedSteps as OnboardingStep[]); setOnboardingForm({ currentStep: onboarding.data.currentStep, goals: onboarding.data.goals ?? "", reviewNote: onboarding.data.reviewNote ?? "" }); } }, [onboarding.data?.completedAt, onboarding.data?.currentStep]);
  useEffect(() => { if (guidelines.data) setBrand({ colors: guidelines.data.colors.join(", "), fonts: guidelines.data.fonts.join(", "), toneOfVoice: guidelines.data.toneOfVoice ?? "", prohibitedWords: guidelines.data.prohibitedWords.join(", "), approvedCtas: guidelines.data.approvedCtas.join(", "), products: guidelines.data.products.join(", "), differentiators: guidelines.data.differentiators.join(", ") }); }, [guidelines.data?.updatedAt]);
  useEffect(() => { if (notifications.data) setNotificationEvents(notifications.data.events as Record<NotificationEvent, boolean>); }, [notifications.data?.updatedAt]);
  useEffect(() => { if (!approvalForm.campaignId && agency.data?.campaigns[0]) setApprovalForm(current => ({ ...current, campaignId: String(agency.data!.campaigns[0].campaign.id) })); }, [agency.data?.campaigns, approvalForm.campaignId]);
  useEffect(() => { if (creativeVersions.data?.[0] && !creativeVersions.data.some(item => String(item.id) === approvalForm.creativeVersionId)) setApprovalForm(current => ({ ...current, creativeVersionId: String(creativeVersions.data![0].id) })); }, [creativeVersions.data, approvalForm.creativeVersionId]);

  const refresh = async () => { await Promise.all([utils.success.health.invalidate(), utils.success.accessGrants.invalidate(), utils.success.onboarding.invalidate(), utils.success.brandGuidelines.invalidate(), utils.success.notificationPreferences.invalidate(), utils.success.executiveReports.invalidate(), utils.success.externalApprovalLinks.invalidate()]); };
  const saveGrant = trpc.success.saveAccessGrant.useMutation({ onSuccess: async () => { await refresh(); setGrant({ email: "", displayName: "", role: "viewer" }); toast.success("Convite registrado. O acesso só será ativado após a aceitação do contato."); }, onError: error => toast.error(error.message) });
  const changeGrant = trpc.success.updateAccessGrantStatus.useMutation({ onSuccess: refresh, onError: error => toast.error(error.message) });
  const saveOnboarding = trpc.success.saveOnboarding.useMutation({ onSuccess: async () => { await refresh(); toast.success("Progresso do onboarding salvo."); }, onError: error => toast.error(error.message) });
  const saveBrand = trpc.success.saveBrandGuidelines.useMutation({ onSuccess: async () => { await refresh(); toast.success("Diretrizes de marca atualizadas para este cliente."); }, onError: error => toast.error(error.message) });
  const saveNotifications = trpc.success.saveNotificationPreferences.useMutation({ onSuccess: async () => { await refresh(); toast.success("Preferências de notificação atualizadas."); }, onError: error => toast.error(error.message) });
  const createReport = trpc.success.createExecutiveReport.useMutation({ onSuccess: async () => { await refresh(); setReportForm(current => ({ ...current, summary: "" })); toast.success("Relatório executivo registrado sob demanda."); }, onError: error => toast.error(error.message) });
  const createApproval = trpc.success.createExternalApprovalLink.useMutation({ onSuccess: async result => { await refresh(); const url = `${window.location.origin}/aprovar/${result.token}`; setCreatedApprovalUrl(url); toast.success("Link de aprovação criado. Copie-o e envie apenas ao responsável informado."); }, onError: error => toast.error(error.message) });
  const revokeApproval = trpc.success.revokeExternalApprovalLink.useMutation({ onSuccess: async () => { await refresh(); toast.success("Link externo revogado."); }, onError: error => toast.error(error.message) });

  function submitGrant(event: FormEvent) { event.preventDefault(); if (clientId) saveGrant.mutate({ clientId, ...grant, displayName: grant.displayName || null }); }
  function submitOnboarding(event: FormEvent) { event.preventDefault(); if (clientId) saveOnboarding.mutate({ clientId, currentStep: completedSteps.length === onboardingSteps.length ? "complete" : onboardingForm.currentStep, completedSteps, goals: onboardingForm.goals || null, reviewNote: onboardingForm.reviewNote || null }); }
  function submitBrand(event: FormEvent) { event.preventDefault(); if (clientId) saveBrand.mutate({ clientId, colors: splitGuidelineList(brand.colors), fonts: splitGuidelineList(brand.fonts), toneOfVoice: brand.toneOfVoice || null, prohibitedWords: splitGuidelineList(brand.prohibitedWords), approvedCtas: splitGuidelineList(brand.approvedCtas), products: splitGuidelineList(brand.products), differentiators: splitGuidelineList(brand.differentiators) }); }
  function submitReport(event: FormEvent) { event.preventDefault(); if (clientId) createReport.mutate({ clientId, title: reportForm.title, summary: reportForm.summary, periodStart: new Date(`${reportForm.periodStart}T00:00:00`), periodEnd: new Date(`${reportForm.periodEnd}T23:59:59`), metrics: { healthScore: health.data?.score ?? null, openTickets: health.data?.support.open ?? 0, pendingApprovals: health.data?.approvals.pending ?? 0, monthlyAiRequests: health.data?.ai.monthlyRequests ?? 0 } }); }
  function submitApproval(event: FormEvent) { event.preventDefault(); if (!clientId || !approvalForm.campaignId || !approvalForm.creativeVersionId) return; createApproval.mutate({ clientId, campaignId: Number(approvalForm.campaignId), creativeVersionId: Number(approvalForm.creativeVersionId), recipientEmail: approvalForm.recipientEmail, expiresAt: new Date(approvalForm.expiresAt) }); }
  async function downloadBackup() { if (!clientId) return; const result = await backup.refetch(); if (!result.data) return toast.error(result.error?.message ?? "Não foi possível preparar a exportação."); const blob = new Blob([JSON.stringify(result.data, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `vertex-${selectedClient?.name.toLowerCase().replace(/[^a-z0-9]+/gi, "-") ?? "cliente"}-backup.json`; anchor.click(); URL.revokeObjectURL(url); toast.success("Exportação segura preparada. Credenciais e segredos não são incluídos."); }

  return <StudioShell title="Sucesso do cliente" eyebrow="Governança multicliente"><div className="success-page">
    <section className="success-intro"><div><p className="wa-kicker"><ShieldCheck size={14} /> relacionamento, segurança e continuidade</p><h2>Transforme operação em uma experiência de cliente previsível.</h2><p>Monitore saúde, formalize acessos, registre a marca e mantenha aprovações, suporte e relatórios no mesmo espaço isolado por cliente.</p></div><label className="success-client-picker">Cliente<select value={clientId ?? ""} onChange={event => { setClientId(Number(event.target.value)); setCreatedApprovalUrl(null); }} disabled={!clients.data?.length}><option value="" disabled>Selecione um cliente</option>{(clients.data ?? []).map(client => <option key={client.id} value={client.id}>{client.name}</option>)}</select></label></section>
    {!clientId ? <div className="wa-panel wa-empty"><Loader2 size={18} /> Carregando clientes do espaço de trabalho…</div> : <>
      <section className="success-health-grid" aria-label="Indicadores de saúde do cliente">
        <article className="success-health-card"><span><Gauge size={16} /></span><small>Saúde da conta</small><strong>{health.data?.score ?? "—"}<small className={`success-status ${health.data?.status ?? ""}`}>{health.data?.status === "healthy" ? "Saudável" : health.data?.status === "attention" ? "Atenção" : health.data?.status === "risk" ? "Risco" : "Atualizando"}</small></strong></article>
        <article className="success-health-card"><span><ClipboardCheck size={16} /></span><small>Onboarding</small><strong>{health.data?.onboarding.complete ? "Concluído" : `${health.data?.onboarding.completedSteps.length ?? 0}/6`}</strong><p>{health.data?.onboarding.complete ? "Base operacional validada." : "Etapas ainda exigem confirmação."}</p></article>
        <article className="success-health-card"><span><TicketCheck size={16} /></span><small>Suporte</small><strong>{health.data?.support.open ?? "—"} aberto{health.data?.support.open === 1 ? "" : "s"}</strong><p>{health.data?.support.urgentOrHigh ?? 0} de prioridade alta ou urgente.</p></article>
        <article className="success-health-card"><span><KeyRound size={16} /></span><small>IA no mês</small><strong>{health.data?.ai.monthlyRequests ?? "—"}</strong><p>{health.data?.ai.monthlyLimit ? `${health.data.ai.usagePercent ?? 0}% do limite contratado.` : "Sem limite mensal definido."}</p></article>
        <article className="success-health-card"><span><Link2 size={16} /></span><small>Aprovações</small><strong>{health.data?.approvals.pending ?? "—"}</strong><p>Versões em revisão humana interna.</p></article>
      </section>

      <section className="success-grid">
        <article className="wa-panel"><div className="wa-panel-heading"><div><p className="wa-kicker"><ClipboardCheck size={14} /> jornada assistida</p><h3>Onboarding operacional</h3><p>Registre as validações essenciais. A conclusão depende de todas as seis etapas e não ativa publicação automática.</p></div><span className="success-section-icon"><ClipboardCheck size={17} /></span></div><form className="success-form" onSubmit={submitOnboarding}>{onboardingSteps.map(step => <label className="success-step" key={step.key}><input type="checkbox" checked={completedSteps.includes(step.key)} onChange={event => setCompletedSteps(current => event.target.checked ? current.includes(step.key) ? current : current.concat(step.key) : current.filter(item => item !== step.key))} /><span><strong>{step.label}</strong><small>{step.description}</small></span></label>)}<div className="success-form-grid"><label>Etapa em condução<select value={onboardingForm.currentStep} onChange={event => setOnboardingForm(current => ({ ...current, currentStep: event.target.value as OnboardingStep }))}>{onboardingSteps.map(step => <option key={step.key} value={step.key}>{step.label}</option>)}<option value="complete">Concluir onboarding</option></select></label><label>Objetivos acordados<input value={onboardingForm.goals} onChange={event => setOnboardingForm(current => ({ ...current, goals: event.target.value }))} placeholder="Ex.: aumentar qualidade dos leads" /></label></div><label>Nota de revisão<textarea value={onboardingForm.reviewNote} onChange={event => setOnboardingForm(current => ({ ...current, reviewNote: event.target.value }))} placeholder="Pendências ou validação da equipe VERTEX" /></label><button className="ops-primary-button" type="submit" disabled={saveOnboarding.isPending}>{saveOnboarding.isPending ? <Loader2 size={15} /> : <Check size={15} />} Salvar progresso</button></form></article>
        <article className="wa-panel"><div className="wa-panel-heading"><div><p className="wa-kicker"><UsersRound size={14} /> acesso sob controle</p><h3>Pessoas autorizadas</h3><p>O convite fica pendente até o titular entrar e aceitar o acesso com o mesmo e-mail.</p></div><span className="success-section-icon"><UsersRound size={17} /></span></div><div className="success-list">{grants.isLoading ? <div className="wa-empty"><Loader2 size={15} /> Atualizando acessos…</div> : !(grants.data?.length) ? <div className="wa-empty"><UsersRound size={16} /> Nenhuma pessoa adicional autorizada.</div> : grants.data.map(item => <div className="success-list-row" key={item.id}><span><UsersRound size={15} /></span><div><strong>{item.displayName || item.email}</strong><p>{item.email} · {item.role.replace("_", " ")}</p></div><button type="button" className={`success-status ${item.status}`} onClick={() => changeGrant.mutate({ clientId, grantId: item.id, status: item.status === "revoked" ? "pending" : "revoked" })}>{item.status === "revoked" ? "Reativar convite" : item.status}</button></div>)}</div><form className="success-form" onSubmit={submitGrant}><h4><UserPlus size={15} /> Convidar contato</h4><div className="success-form-grid"><label>Nome<input value={grant.displayName} onChange={event => setGrant(current => ({ ...current, displayName: event.target.value }))} placeholder="Nome do responsável" /></label><label>E-mail<input type="email" required value={grant.email} onChange={event => setGrant(current => ({ ...current, email: event.target.value }))} placeholder="responsavel@empresa.com" /></label></div><label>Papel<select value={grant.role} onChange={event => setGrant(current => ({ ...current, role: event.target.value as GrantRole }))}><option value="client_admin">Administrador do cliente</option><option value="manager">Gestor</option><option value="reviewer">Revisor</option><option value="viewer">Somente leitura</option></select></label><button className="ops-secondary-button" type="submit" disabled={saveGrant.isPending}>{saveGrant.isPending ? <Loader2 size={15} /> : <UserPlus size={15} />} Registrar convite</button></form></article>
      </section>

      <section className="success-grid">
        <article className="wa-panel"><div className="wa-panel-heading"><div><p className="wa-kicker"><Palette size={14} /> consistência criativa</p><h3>Diretrizes expandidas de marca</h3><p>Estas regras complementam os ativos autorizados da Agência IA e orientam toda revisão humana.</p></div><span className="success-section-icon"><Palette size={17} /></span></div><form className="success-form" onSubmit={submitBrand}><div className="success-form-grid"><label>Cores autorizadas<input value={brand.colors} onChange={event => setBrand(current => ({ ...current, colors: event.target.value }))} placeholder="#123456, verde escuro" /></label><label>Tipografias<input value={brand.fonts} onChange={event => setBrand(current => ({ ...current, fonts: event.target.value }))} placeholder="Inter, Merriweather" /></label></div><label>Tom de voz<textarea value={brand.toneOfVoice} onChange={event => setBrand(current => ({ ...current, toneOfVoice: event.target.value }))} placeholder="Como a marca deve soar" /></label><div className="success-form-grid"><label>Palavras proibidas<input value={brand.prohibitedWords} onChange={event => setBrand(current => ({ ...current, prohibitedWords: event.target.value }))} placeholder="desconto, milagre" /></label><label>CTAs aprovados<input value={brand.approvedCtas} onChange={event => setBrand(current => ({ ...current, approvedCtas: event.target.value }))} placeholder="Fale com um especialista" /></label><label>Produtos e serviços<input value={brand.products} onChange={event => setBrand(current => ({ ...current, products: event.target.value }))} placeholder="Linha premium, instalação" /></label><label>Diferenciais<input value={brand.differentiators} onChange={event => setBrand(current => ({ ...current, differentiators: event.target.value }))} placeholder="Garantia, atendimento consultivo" /></label></div><button className="ops-primary-button" type="submit" disabled={saveBrand.isPending}>{saveBrand.isPending ? <Loader2 size={15} /> : <Check size={15} />} Salvar diretrizes</button></form></article>
        <article className="wa-panel"><div className="wa-panel-heading"><div><p className="wa-kicker"><BellRing size={14} /> sinais relevantes</p><h3>Notificações por cliente</h3><p>Defina quais eventos podem criar alertas no centro de sinais da VERTEX. Nenhum aviso é disparado por agendamento nesta versão.</p></div><span className="success-section-icon"><BellRing size={17} /></span></div><div className="success-preferences">{(Object.keys(notificationLabels) as NotificationEvent[]).map(key => <label className="success-preference" key={key}><input type="checkbox" checked={notificationEvents[key]} onChange={event => setNotificationEvents(current => ({ ...current, [key]: event.target.checked }))} />{notificationLabels[key]}</label>)}</div><button type="button" className="ops-primary-button" onClick={() => clientId && saveNotifications.mutate({ clientId, events: notificationEvents })} disabled={saveNotifications.isPending}>{saveNotifications.isPending ? <Loader2 size={15} /> : <BellRing size={15} />} Salvar preferências</button></article>
      </section>

      <section className="success-grid">
        <article className="wa-panel"><div className="wa-panel-heading"><div><p className="wa-kicker"><ExternalLink size={14} /> revisão externa</p><h3>Links seguros de aprovação</h3><p>O link é exclusivo, expira na data definida e aceita uma única decisão. A publicação continua dependente da equipe VERTEX.</p></div><span className="success-section-icon"><Link2 size={17} /></span></div><form className="success-form" onSubmit={submitApproval}><div className="success-form-grid"><label>Campanha<select required value={approvalForm.campaignId} onChange={event => setApprovalForm(current => ({ ...current, campaignId: event.target.value, creativeVersionId: "" }))}><option value="">Selecione</option>{(agency.data?.campaigns ?? []).map(item => <option key={item.campaign.id} value={item.campaign.id}>{item.campaign.name}</option>)}</select></label><label>Versão criativa<select required value={approvalForm.creativeVersionId} onChange={event => setApprovalForm(current => ({ ...current, creativeVersionId: event.target.value }))}><option value="">Selecione</option>{(creativeVersions.data ?? []).filter(item => item.status === "review" || item.status === "draft").map(item => <option key={item.id} value={item.id}>Versão {item.versionNumber} · {item.status}</option>)}</select></label><label>Responsável externo<input type="email" required value={approvalForm.recipientEmail} onChange={event => setApprovalForm(current => ({ ...current, recipientEmail: event.target.value }))} placeholder="cliente@empresa.com" /></label><label>Expira em<input type="datetime-local" required value={approvalForm.expiresAt} onChange={event => setApprovalForm(current => ({ ...current, expiresAt: event.target.value }))} /></label></div><button className="ops-primary-button" type="submit" disabled={createApproval.isPending}>{createApproval.isPending ? <Loader2 size={15} /> : <Link2 size={15} />} Gerar link de aprovação</button></form>{createdApprovalUrl ? <div className="success-created-link"><strong>Copie agora o link protegido</strong><code>{createdApprovalUrl}</code><button className="ops-secondary-button" type="button" onClick={() => navigator.clipboard.writeText(createdApprovalUrl).then(() => toast.success("Link copiado."))}>Copiar link</button></div> : null}<div className="success-list">{(approvals.data ?? []).slice(0, 5).map(item => <div className="success-list-row" key={item.id}><span><Link2 size={15} /></span><div><strong>{item.campaignName} · versão {item.creativeVersionId}</strong><p>{item.recipientEmail} · expira {formatDate(item.expiresAt, true)}</p></div><button type="button" className={`success-status ${item.status}`} disabled={item.status !== "open" || revokeApproval.isPending} onClick={() => revokeApproval.mutate({ clientId, linkId: item.id })}>{item.status === "open" ? "Revogar" : item.status}</button></div>)}</div></article>
        <article className="wa-panel"><div className="wa-panel-heading"><div><p className="wa-kicker"><FileText size={14} /> sob demanda</p><h3>Relatórios e exportação</h3><p>Registre uma leitura executiva do período e exporte um retrato seguro dos dados operacionais. Credenciais, tokens e cifras são sempre excluídos.</p></div><span className="success-section-icon"><FileText size={17} /></span></div><form className="success-form" onSubmit={submitReport}><label>Título<input required value={reportForm.title} onChange={event => setReportForm(current => ({ ...current, title: event.target.value }))} /></label><div className="success-form-grid"><label>Início<input required type="date" value={reportForm.periodStart} onChange={event => setReportForm(current => ({ ...current, periodStart: event.target.value }))} /></label><label>Fim<input required type="date" value={reportForm.periodEnd} onChange={event => setReportForm(current => ({ ...current, periodEnd: event.target.value }))} /></label></div><label>Resumo executivo<textarea required value={reportForm.summary} onChange={event => setReportForm(current => ({ ...current, summary: event.target.value }))} placeholder="Principais resultados, riscos e próximos passos." /></label><button className="ops-primary-button" type="submit" disabled={createReport.isPending}>{createReport.isPending ? <Loader2 size={15} /> : <FileText size={15} />} Registrar relatório</button></form><div className="success-list">{(reports.data ?? []).slice(0, 4).map(item => <div className="success-list-row" key={item.id}><span><FileText size={15} /></span><div><strong>{item.title}</strong><p>{formatDate(item.periodStart)} — {formatDate(item.periodEnd)}</p></div><small>{formatDate(item.createdAt)}</small></div>)}</div><button type="button" className="ops-secondary-button" onClick={downloadBackup} disabled={backup.isFetching}><FileDown size={15} /> {backup.isFetching ? "Preparando…" : "Exportar backup seguro (.json)"}</button><p className="success-export-note">A exportação serve a portabilidade administrativa e inclui instruções de restauração. Ela não recria automaticamente configurações secretas.</p></article>
      </section>
      {health.data?.nextActions.length ? <section className="success-action-list"><strong>Próximas ações recomendadas para {selectedClient?.name}</strong><ul>{health.data.nextActions.map(action => <li key={action}>{action}</li>)}</ul><Link className="success-link" href="/suporte">Abrir central de suporte <ExternalLink size={12} /></Link></section> : null}
    </>}
  </div></StudioShell>;
}
